class Team < ApplicationRecord

  def self.all_teams
    Team.where.not(group: 'place_holder')
  end

  def self.winner_options
    Team.where(name: ['france', 'england', 'belgium', 'spain', 'portugal', 'italy', 'germany'])
  end

  def self.black_horses
    Team.where(name: ['north_macedonia', 'finland', 'hungary'])
  end

  def self.grey_horses
    Team.where(name: ['slovakia', 'scotland', 'czech_republic', 'sweden', 'austria', 'turkey', 'russia', 'switzerland', 'wales'])
  end

  def self.top_scorer_options
    ['Harry Kane',
    'Romelu Lukaku',
    'Kylian Mbappé',
    'Cristiano Ronaldo',
    'Karim Benzema',
    'Memphis Depay',
    'Ciro Immobile',
    'Robert Lewandowski',
    'Antoine Griezmann',
    'Álvaro Morata',
    'Timo Werner',
    'Wout Weghorst',
    'Diogo Jota',
    'Ferran Torres',
    'Andrej Kramarić',
    'Serge Gnabry',
    'Kai Havertz',
    'Gerard Moreno',
    'Burak Yılmaz',
    'Thomas Müller',
    'Eden Hazard',
    'Marcus Rashford',
    'Gareth Bale',
    'Andrea Belotti',
    'Dries Mertens',
    'Raheem Sterling',
    'Lorenzo Insigne',
    'Phil Foden',
    'Sasa Kalajdzic',
    'Haris Seferović',
    'Kevin De Bruyne',
    'Bruno Fernandes',
    'Alexander Isak',
    'João Félix',
    'Leroy Sané',
    'Patrik Schick  ',
    'Donyell Malen',
    'Artem Dzyuba',
    'Christian Eriksen',
    'Roman Yaremchuk',
    'Olivier Giroud',
    'Mason Greenwood',
    'Yussuf Poulsen',
    'Ante Rebić',
    'Jadon Sancho',
    'Michy Batshuayi',
    'Georginho Wijnaldum',
    'Breel Embolo',
    'Emil Forsberg',
    'Dani Olmo',
    'Martin Braithwaite',
    'Divock Origi',
    'Teemu Pukki',
    'Paul Pogba',
    'Bernardo Silva',
    'Marcus Berg',
    'Denis Cheryshev',
    'Luka Modrić',
    'Andriy Yarmolenko',
    'Aaron Ramsey',
    'Jordan LarssonHarry Kane',
    'Romelu Lukaku',
    'Kylian Mbappé',
    'Cristiano Ronaldo',
    'Karim Benzema',
    'Memphis Depay',
    'Ciro Immobile',
    'Robert Lewandowski',
    'Antoine Griezmann',
    'Álvaro Morata',
    'Timo Werner',
    'Wout Weghorst',
    'Diogo Jota',
    'Ferran Torres',
    'Andrej Kramarić',
    'Serge Gnabry',
    'Kai Havertz',
    'Gerard Moreno',
    'Burak Yılmaz',
    'Thomas Müller',
    'Eden Hazard',
    'Marcus Rashford',
    'Gareth Bale',
    'Andrea Belotti',
    'Dries Mertens',
    'Raheem Sterling',
    'Lorenzo Insigne',
    'Phil Foden',
    'Sasa Kalajdzic',
    'Haris Seferović',
    'Kevin De Bruyne',
    'Bruno Fernandes',
    'Alexander Isak',
    'João Félix',
    'Leroy Sané',
    'Patrik Schick',
    'Donyell Malen',
    'Artem Dzyuba',
    'Christian Eriksen',
    'Roman Yaremchuk',
    'Olivier Giroud',
    'Mason Greenwood',
    'Yussuf Poulsen',
    'Ante Rebić',
    'Jadon Sancho',
    'Michy Batshuayi',
    'Georginho Wijnaldum',
    'Breel Embolo',
    'Emil Forsberg',
    'Dani Olmo',
    'Martin Braithwaite',
    'Divock Origi',
    'Teemu Pukki',
    'Paul Pogba',
    'Bernardo Silva',
    'Marcus Berg',
    'Denis Cheryshev',
    'Luka Modrić',
    'Andriy Yarmolenko',
    'Aaron Ramsey',
    'Jordan Larsson']
  end

end
